[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "Rosalind"
author = "Daniel Crookston"
author-email = "dcrookston@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]

